<?php

namespace Stepit\Bundle\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatterRepository extends EntityRepository
{
}
