steppie_app:
    resource: "@SteppieAppBundle/Resources/config/routing/routing.yml"
    prefix:   /

easy_admin:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
